USE everyLastDrop;

DESC glass;
SELECT * FROM glass;
DESC drinkRecipe;
SELECT * FROM drinkRecipe;
DESC drinkRequires;
SELECT * FROM drinkRequires;
DESC ingredient;
SELECT * FROM ingredient;
DESC alcohol;
SELECT * FROM alcohol;
DESC juice;
SELECT * FROM juice;
DESC garnish;
SELECT * FROM garnish;
DESC customer;
SELECT * FROM customer;
DESC transaction;
SELECT * FROM transaction;
