name: Push Container to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        ADMIN_PASS: ${{ secrets.ADMIN_PASSWORD }}
        ADMIN_USER: ${{ secrets.ADMIN_NAME }}
    - name: Build and push
      run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        ADMIN_PASS: ${{ secrets.ADMIN_PASSWORD }}
        ADMIN_USER: ${{ secrets.ADMIN_NAME }}
    - name: Release
      run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        ADMIN_PASS: ${{ secrets.ADMIN_PASSWORD }}
        ADMIN_USER: ${{ secrets.ADMIN_NAME }}
