name: Push Container to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Login to Heroku Container registry
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        ADMIN_PASS: ${{ secrets.ADMIN_PASSWORD }}
        ADMIN_USER: ${{ secrets.ADMIN_NAME }}
        APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        SQL_HOSTNAME: ${{ secrets.SQL_HOSTNAME }}
        SQL_SSH_STRING: ${{ secrets.SQL_SSH_STRING }}
        SQL_PORT: ${{ secrets.SQL_PORT }}
      run: |
        echo "${{ env.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com
        docker build --build-arg ADMIN_PASS=${{ env.ADMIN_PASS }} --build-arg ADMIN_USER=${{ env.ADMIN_USER }} --build-arg SQL_HOSTNAME=${{ env.SQL_HOSTNAME }} SQL_PORT=${{ env.SQL_PORT }} --build-arg SQL_SSH_STRING="${{ env.SQL_SSH_STRING }}" -t registry.heroku.com/${{ env.APP_NAME }}/web .
        docker push registry.heroku.com/${{ env.APP_NAME }}/web

    - name: Release
      run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
